### ISSUE TITLE
类名、方法名规范化问题

### ISSUE THREAD

**Issue by UtenaTenjo371** [UtenaTenjo371/GitManagement#10]
1. 类Task1起名不明确，方法名与类名应当改为直观的名字，如KeyValueStored与catFile。
2. 类saveObject没有大写开头，与其他类不符
3. 不知道是否要将Task1.class中的两个类拆开？@Windyabc @YanbingChen

@js00070

**Comment by js00070** [comment]
嗯，尽量能拆开的就拆开吧
