### ISSUE TITLE
最终文档

### ISSUE THREAD

**Issue by YanbingChen** [UtenaTenjo371/GitManagement#18]
- 补齐设计文档，包括Branch、CovertFolder、VersionController…… @UtenaTenjo371 
- 完成单元测试和相应的文档 @Windyabc 
- 完成git add @Windyabc 
- 补齐GitLog、SaveString的设计文档，完善GitLog注释，更新Task1（要不要重新命名成Key-Value存储实现？）的设计文档。 @YanbingChen 
- 早一点点完成（尽可能周六？）方便我最后整理呗，大家顺便写一下自己分工？或者张老师写一下？自己部分里有啥亮点也标标？
- 整理汇总文档，标注实现的功能，模块划分及类/接口设计（类图），亮点。文档+ppt要在1.10前发助教邮箱。 @YanbingChen

**Comment by Wynteroz** [comment]
收到
