### ISSUE TITLE
key-value没有持久化存储

### ISSUE THREAD

**Issue by Wynteroz** [UtenaTenjo371/GitManagement#6]
BinarySearchST只是在内存里存了key-value结构，没有持久化存储在磁盘上，程序重启了key-value就都没了。。。

_Originally posted by @js00070 in https://github.com/UtenaTenjo371/GitManagement/issues/5#issuecomment-741754435_

**Comment by js00070** [comment]
此issue已被https://github.com/UtenaTenjo371/GitManagement/pull/8 修复
